services:
  synapse:
    image: ghcr.io/jpcshka/synapse-s3:v1.157.2
    expose:
      - "8008"
      - "9000"
    volumes:
      - /var/lib/matrix-compose/data:/data 
    restart: unless-stopped
    networks:
      - synapse
      - monitoring
  
  caddy:
    image: caddy:2.11.4
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 
    environment:
      - SYNAPSE_ADDRESS=${SYNAPSE_ADDRESS}
      - LIVEKIT_ADDRESS=${LIVEKIT_ADDRESS}
      - LK_JWT_ADDRESS=${LK_JWT_ADDRESS}
      - GRAFANA_ADDRESS=${GRAFANA_ADDRESS}
      - MAIN_URL=${MAIN_URL}
      - SYNAPSE_URL=${SYNAPSE_URL}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - GRAFANA_URL=${GRAFANA_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - GRAFANA_PASSWORD_HASH=${GRAFANA_PASSWORD_HASH}
    volumes:
      - ./caddy:/etc/caddy 
      - ./static:/srv 
      - caddy_data:/data 
      - caddy_config:/config
    depends_on: 
      synapse:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - synapse
      - livekit
      - lkjwt
      - grafana
      - monitoring

  livekit:
    image: livekit/livekit-server:v1.13.4
    command: --config /etc/livekit.yaml
    ports:
      - "7881:7881" 
      - "50100-50101:50100-50101/udp" # udp_ports
    expose:
      - 7880
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    restart: unless-stopped
    networks:
      - livekit
      - monitoring

  lkjwt:
    image: ghcr.io/element-hq/lk-jwt-service:0.5.0
    environment:
      - LIVEKIT_JWT_BIND=${LIVEKIT_JWT_BIND}
      - LIVEKIT_URL=${LIVEKIT_WSS_URL}
      - LIVEKIT_KEY=${LIVEKIT_DEVKEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=${MAIN_URL}
    expose:
      - 6080
    depends_on:
      - livekit
    restart: unless-stopped
    networks:
      - lkjwt
  
  prometheus:
    image: prom/prometheus:v3.13.1
    command: --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    extra_hosts:
      - "postgresdb:${POSTGRES_DB_IP}"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
      - graf

  node_exporter:
    image: prom/node-exporter:v1.12.1
    command: --path.rootfs=/host
    expose:
      - 9100
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:13.1.1
    expose:
      - 3000
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - grafana
      - graf


networks:
  synapse:
  livekit:
  lkjwt:
  grafana:
  monitoring:
  graf:

volumes:
  caddy_data:
  caddy_config:
  prometheus_data:
  grafana-storage:

# image, build and command
# ports 
# environment variables
# expose
# volumes
# healthcheck
# depends_on
# restart 
# networks
